language: java
jdk:
- openjdk7
- oraclejdk7

script:
- ./gradlew check
<<<<<<< HEAD
//- ./gradlew seleniumXvfb
=======
- ./gradlew seleniumXvfb
- ./gradlew test jacocoTestReport
>>>>>>> 2d048c6e3d5f7f4656cfb8d0252826c44c62943f

deploy:
   provider: heroku
   api_key: 67af61f8-113d-4e39-b755-80c206800211
   run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"

app: fantasticseven

after_deploy: 
- ./gradlew seleniumXvfb
